//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BD_CondominioModel", "FK_tabAlaQuarto_tabAla", "tabAla", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SistemaCondominioDAO.tabAla), "tabAlaQuarto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SistemaCondominioDAO.tabAlaQuarto), true)]
[assembly: EdmRelationshipAttribute("BD_CondominioModel", "FK_tabCondominio_tabAlaQuarto", "tabAlaQuarto", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SistemaCondominioDAO.tabAlaQuarto), "tabCondominio", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SistemaCondominioDAO.tabCondominio), true)]
[assembly: EdmRelationshipAttribute("BD_CondominioModel", "FK_tabCondominio_tabCliente", "tabCliente", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SistemaCondominioDAO.tabCliente), "tabCondominio", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SistemaCondominioDAO.tabCondominio), true)]
[assembly: EdmRelationshipAttribute("BD_CondominioModel", "FK_tabTelefone_tabCliente", "tabCliente", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SistemaCondominioDAO.tabCliente), "tabTelefone", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SistemaCondominioDAO.tabTelefone), true)]

#endregion

namespace SistemaCondominioDAO
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BD_CondominioEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BD_CondominioEntities object using the connection string found in the 'BD_CondominioEntities' section of the application configuration file.
        /// </summary>
        public BD_CondominioEntities() : base("name=BD_CondominioEntities", "BD_CondominioEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BD_CondominioEntities object.
        /// </summary>
        public BD_CondominioEntities(string connectionString) : base(connectionString, "BD_CondominioEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BD_CondominioEntities object.
        /// </summary>
        public BD_CondominioEntities(EntityConnection connection) : base(connection, "BD_CondominioEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tabAla> tabAla
        {
            get
            {
                if ((_tabAla == null))
                {
                    _tabAla = base.CreateObjectSet<tabAla>("tabAla");
                }
                return _tabAla;
            }
        }
        private ObjectSet<tabAla> _tabAla;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tabAlaQuarto> tabAlaQuarto
        {
            get
            {
                if ((_tabAlaQuarto == null))
                {
                    _tabAlaQuarto = base.CreateObjectSet<tabAlaQuarto>("tabAlaQuarto");
                }
                return _tabAlaQuarto;
            }
        }
        private ObjectSet<tabAlaQuarto> _tabAlaQuarto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tabCliente> tabCliente
        {
            get
            {
                if ((_tabCliente == null))
                {
                    _tabCliente = base.CreateObjectSet<tabCliente>("tabCliente");
                }
                return _tabCliente;
            }
        }
        private ObjectSet<tabCliente> _tabCliente;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tabCondominio> tabCondominio
        {
            get
            {
                if ((_tabCondominio == null))
                {
                    _tabCondominio = base.CreateObjectSet<tabCondominio>("tabCondominio");
                }
                return _tabCondominio;
            }
        }
        private ObjectSet<tabCondominio> _tabCondominio;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tabTelefone> tabTelefone
        {
            get
            {
                if ((_tabTelefone == null))
                {
                    _tabTelefone = base.CreateObjectSet<tabTelefone>("tabTelefone");
                }
                return _tabTelefone;
            }
        }
        private ObjectSet<tabTelefone> _tabTelefone;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tabAla EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotabAla(tabAla tabAla)
        {
            base.AddObject("tabAla", tabAla);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tabAlaQuarto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotabAlaQuarto(tabAlaQuarto tabAlaQuarto)
        {
            base.AddObject("tabAlaQuarto", tabAlaQuarto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tabCliente EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotabCliente(tabCliente tabCliente)
        {
            base.AddObject("tabCliente", tabCliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tabCondominio EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotabCondominio(tabCondominio tabCondominio)
        {
            base.AddObject("tabCondominio", tabCondominio);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tabTelefone EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotabTelefone(tabTelefone tabTelefone)
        {
            base.AddObject("tabTelefone", tabTelefone);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_CondominioModel", Name="tabAla")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tabAla : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tabAla object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tabAla CreatetabAla(global::System.Int32 id)
        {
            tabAla tabAla = new tabAla();
            tabAla.id = id;
            return tabAla;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> numeroAla
        {
            get
            {
                return _numeroAla;
            }
            set
            {
                OnnumeroAlaChanging(value);
                ReportPropertyChanging("numeroAla");
                _numeroAla = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numeroAla");
                OnnumeroAlaChanged();
            }
        }
        private Nullable<global::System.Int32> _numeroAla;
        partial void OnnumeroAlaChanging(Nullable<global::System.Int32> value);
        partial void OnnumeroAlaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_CondominioModel", "FK_tabAlaQuarto_tabAla", "tabAlaQuarto")]
        public EntityCollection<tabAlaQuarto> tabAlaQuarto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tabAlaQuarto>("BD_CondominioModel.FK_tabAlaQuarto_tabAla", "tabAlaQuarto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tabAlaQuarto>("BD_CondominioModel.FK_tabAlaQuarto_tabAla", "tabAlaQuarto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_CondominioModel", Name="tabAlaQuarto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tabAlaQuarto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tabAlaQuarto object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tabAlaQuarto CreatetabAlaQuarto(global::System.Int32 id)
        {
            tabAlaQuarto tabAlaQuarto = new tabAlaQuarto();
            tabAlaQuarto.id = id;
            return tabAlaQuarto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_ala
        {
            get
            {
                return _id_ala;
            }
            set
            {
                Onid_alaChanging(value);
                ReportPropertyChanging("id_ala");
                _id_ala = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_ala");
                Onid_alaChanged();
            }
        }
        private Nullable<global::System.Int32> _id_ala;
        partial void Onid_alaChanging(Nullable<global::System.Int32> value);
        partial void Onid_alaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nquarto
        {
            get
            {
                return _Nquarto;
            }
            set
            {
                OnNquartoChanging(value);
                ReportPropertyChanging("Nquarto");
                _Nquarto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nquarto");
                OnNquartoChanged();
            }
        }
        private global::System.String _Nquarto;
        partial void OnNquartoChanging(global::System.String value);
        partial void OnNquartoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_CondominioModel", "FK_tabAlaQuarto_tabAla", "tabAla")]
        public tabAla tabAla
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tabAla>("BD_CondominioModel.FK_tabAlaQuarto_tabAla", "tabAla").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tabAla>("BD_CondominioModel.FK_tabAlaQuarto_tabAla", "tabAla").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tabAla> tabAlaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tabAla>("BD_CondominioModel.FK_tabAlaQuarto_tabAla", "tabAla");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tabAla>("BD_CondominioModel.FK_tabAlaQuarto_tabAla", "tabAla", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_CondominioModel", "FK_tabCondominio_tabAlaQuarto", "tabCondominio")]
        public EntityCollection<tabCondominio> tabCondominio
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tabCondominio>("BD_CondominioModel.FK_tabCondominio_tabAlaQuarto", "tabCondominio");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tabCondominio>("BD_CondominioModel.FK_tabCondominio_tabAlaQuarto", "tabCondominio", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_CondominioModel", Name="tabCliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tabCliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tabCliente object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tabCliente CreatetabCliente(global::System.Int32 id)
        {
            tabCliente tabCliente = new tabCliente();
            tabCliente.id = id;
            return tabCliente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sexo
        {
            get
            {
                return _sexo;
            }
            set
            {
                OnsexoChanging(value);
                ReportPropertyChanging("sexo");
                _sexo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sexo");
                OnsexoChanged();
            }
        }
        private global::System.String _sexo;
        partial void OnsexoChanging(global::System.String value);
        partial void OnsexoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cpf
        {
            get
            {
                return _cpf;
            }
            set
            {
                OncpfChanging(value);
                ReportPropertyChanging("cpf");
                _cpf = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cpf");
                OncpfChanged();
            }
        }
        private global::System.String _cpf;
        partial void OncpfChanging(global::System.String value);
        partial void OncpfChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dt_nascimento
        {
            get
            {
                return _dt_nascimento;
            }
            set
            {
                Ondt_nascimentoChanging(value);
                ReportPropertyChanging("dt_nascimento");
                _dt_nascimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dt_nascimento");
                Ondt_nascimentoChanged();
            }
        }
        private Nullable<global::System.DateTime> _dt_nascimento;
        partial void Ondt_nascimentoChanging(Nullable<global::System.DateTime> value);
        partial void Ondt_nascimentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String obs
        {
            get
            {
                return _obs;
            }
            set
            {
                OnobsChanging(value);
                ReportPropertyChanging("obs");
                _obs = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("obs");
                OnobsChanged();
            }
        }
        private global::System.String _obs;
        partial void OnobsChanging(global::System.String value);
        partial void OnobsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String escolaridade
        {
            get
            {
                return _escolaridade;
            }
            set
            {
                OnescolaridadeChanging(value);
                ReportPropertyChanging("escolaridade");
                _escolaridade = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("escolaridade");
                OnescolaridadeChanged();
            }
        }
        private global::System.String _escolaridade;
        partial void OnescolaridadeChanging(global::System.String value);
        partial void OnescolaridadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sitOcupacional
        {
            get
            {
                return _sitOcupacional;
            }
            set
            {
                OnsitOcupacionalChanging(value);
                ReportPropertyChanging("sitOcupacional");
                _sitOcupacional = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sitOcupacional");
                OnsitOcupacionalChanged();
            }
        }
        private global::System.String _sitOcupacional;
        partial void OnsitOcupacionalChanging(global::System.String value);
        partial void OnsitOcupacionalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dt_cadastro
        {
            get
            {
                return _dt_cadastro;
            }
            set
            {
                Ondt_cadastroChanging(value);
                ReportPropertyChanging("dt_cadastro");
                _dt_cadastro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dt_cadastro");
                Ondt_cadastroChanged();
            }
        }
        private Nullable<global::System.DateTime> _dt_cadastro;
        partial void Ondt_cadastroChanging(Nullable<global::System.DateTime> value);
        partial void Ondt_cadastroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_cadastro
        {
            get
            {
                return _user_cadastro;
            }
            set
            {
                Onuser_cadastroChanging(value);
                ReportPropertyChanging("user_cadastro");
                _user_cadastro = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_cadastro");
                Onuser_cadastroChanged();
            }
        }
        private global::System.String _user_cadastro;
        partial void Onuser_cadastroChanging(global::System.String value);
        partial void Onuser_cadastroChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_CondominioModel", "FK_tabCondominio_tabCliente", "tabCondominio")]
        public EntityCollection<tabCondominio> tabCondominio
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tabCondominio>("BD_CondominioModel.FK_tabCondominio_tabCliente", "tabCondominio");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tabCondominio>("BD_CondominioModel.FK_tabCondominio_tabCliente", "tabCondominio", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_CondominioModel", "FK_tabTelefone_tabCliente", "tabTelefone")]
        public EntityCollection<tabTelefone> tabTelefone
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tabTelefone>("BD_CondominioModel.FK_tabTelefone_tabCliente", "tabTelefone");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tabTelefone>("BD_CondominioModel.FK_tabTelefone_tabCliente", "tabTelefone", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_CondominioModel", Name="tabCondominio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tabCondominio : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tabCondominio object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tabCondominio CreatetabCondominio(global::System.Int32 id)
        {
            tabCondominio tabCondominio = new tabCondominio();
            tabCondominio.id = id;
            return tabCondominio;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_cliente
        {
            get
            {
                return _id_cliente;
            }
            set
            {
                Onid_clienteChanging(value);
                ReportPropertyChanging("id_cliente");
                _id_cliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_cliente");
                Onid_clienteChanged();
            }
        }
        private Nullable<global::System.Int32> _id_cliente;
        partial void Onid_clienteChanging(Nullable<global::System.Int32> value);
        partial void Onid_clienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_AlaQ
        {
            get
            {
                return _id_AlaQ;
            }
            set
            {
                Onid_AlaQChanging(value);
                ReportPropertyChanging("id_AlaQ");
                _id_AlaQ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_AlaQ");
                Onid_AlaQChanged();
            }
        }
        private Nullable<global::System.Int32> _id_AlaQ;
        partial void Onid_AlaQChanging(Nullable<global::System.Int32> value);
        partial void Onid_AlaQChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dataEntrada
        {
            get
            {
                return _dataEntrada;
            }
            set
            {
                OndataEntradaChanging(value);
                ReportPropertyChanging("dataEntrada");
                _dataEntrada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dataEntrada");
                OndataEntradaChanged();
            }
        }
        private Nullable<global::System.DateTime> _dataEntrada;
        partial void OndataEntradaChanging(Nullable<global::System.DateTime> value);
        partial void OndataEntradaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tempo
        {
            get
            {
                return _tempo;
            }
            set
            {
                OntempoChanging(value);
                ReportPropertyChanging("tempo");
                _tempo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tempo");
                OntempoChanged();
            }
        }
        private global::System.String _tempo;
        partial void OntempoChanging(global::System.String value);
        partial void OntempoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dt_cadastro
        {
            get
            {
                return _dt_cadastro;
            }
            set
            {
                Ondt_cadastroChanging(value);
                ReportPropertyChanging("dt_cadastro");
                _dt_cadastro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dt_cadastro");
                Ondt_cadastroChanged();
            }
        }
        private Nullable<global::System.DateTime> _dt_cadastro;
        partial void Ondt_cadastroChanging(Nullable<global::System.DateTime> value);
        partial void Ondt_cadastroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_cadastro
        {
            get
            {
                return _user_cadastro;
            }
            set
            {
                Onuser_cadastroChanging(value);
                ReportPropertyChanging("user_cadastro");
                _user_cadastro = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_cadastro");
                Onuser_cadastroChanged();
            }
        }
        private global::System.String _user_cadastro;
        partial void Onuser_cadastroChanging(global::System.String value);
        partial void Onuser_cadastroChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_CondominioModel", "FK_tabCondominio_tabAlaQuarto", "tabAlaQuarto")]
        public tabAlaQuarto tabAlaQuarto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tabAlaQuarto>("BD_CondominioModel.FK_tabCondominio_tabAlaQuarto", "tabAlaQuarto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tabAlaQuarto>("BD_CondominioModel.FK_tabCondominio_tabAlaQuarto", "tabAlaQuarto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tabAlaQuarto> tabAlaQuartoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tabAlaQuarto>("BD_CondominioModel.FK_tabCondominio_tabAlaQuarto", "tabAlaQuarto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tabAlaQuarto>("BD_CondominioModel.FK_tabCondominio_tabAlaQuarto", "tabAlaQuarto", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_CondominioModel", "FK_tabCondominio_tabCliente", "tabCliente")]
        public tabCliente tabCliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tabCliente>("BD_CondominioModel.FK_tabCondominio_tabCliente", "tabCliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tabCliente>("BD_CondominioModel.FK_tabCondominio_tabCliente", "tabCliente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tabCliente> tabClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tabCliente>("BD_CondominioModel.FK_tabCondominio_tabCliente", "tabCliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tabCliente>("BD_CondominioModel.FK_tabCondominio_tabCliente", "tabCliente", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BD_CondominioModel", Name="tabTelefone")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tabTelefone : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tabTelefone object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tabTelefone CreatetabTelefone(global::System.Int32 id)
        {
            tabTelefone tabTelefone = new tabTelefone();
            tabTelefone.id = id;
            return tabTelefone;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_cliente
        {
            get
            {
                return _id_cliente;
            }
            set
            {
                Onid_clienteChanging(value);
                ReportPropertyChanging("id_cliente");
                _id_cliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_cliente");
                Onid_clienteChanged();
            }
        }
        private Nullable<global::System.Int32> _id_cliente;
        partial void Onid_clienteChanging(Nullable<global::System.Int32> value);
        partial void Onid_clienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telefone
        {
            get
            {
                return _telefone;
            }
            set
            {
                OntelefoneChanging(value);
                ReportPropertyChanging("telefone");
                _telefone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("telefone");
                OntelefoneChanged();
            }
        }
        private global::System.String _telefone;
        partial void OntelefoneChanging(global::System.String value);
        partial void OntelefoneChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BD_CondominioModel", "FK_tabTelefone_tabCliente", "tabCliente")]
        public tabCliente tabCliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tabCliente>("BD_CondominioModel.FK_tabTelefone_tabCliente", "tabCliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tabCliente>("BD_CondominioModel.FK_tabTelefone_tabCliente", "tabCliente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tabCliente> tabClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tabCliente>("BD_CondominioModel.FK_tabTelefone_tabCliente", "tabCliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tabCliente>("BD_CondominioModel.FK_tabTelefone_tabCliente", "tabCliente", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
